### ISSUE TITLE
Meetup for Thursday, 2/12/15

### ISSUE THREAD

**Issue by samt** [beerjs/sac#12]
# BeerJS!

    beerjs.sac.febuary.when();
    > Thu Feb 12 2015 18:00:00 GMT-0800 (PST)
    
    beerjs.sac.febuary.where();
    > Meeting at Pour House: http://pourhousesacramento.com/
    > Map: http://goo.gl/5kIRDU
    
    beerjs.sac.febuary.who();
    > Everyone!
    
    beerjs.sac.febuary.why();
    > Because, `Beer && JS`!

-------------

RSVP here or on [our Meetup](http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/220378062/)!

Clickable Location: [Pour House](http://pourhousesacramento.com/) ([Map](http://goo.gl/5kIRDU))

**Comment by samt** [comment]
Paging @dlindahl @thefatpanther @a-axton

**Comment by efletch** [comment]
I vote Pour House!! or Bier Garden, I haven't been there before

**Comment by machadolab** [comment]
Pour_House++

**Comment by thefatpanther** [comment]
Been wanting to see the Pour House. But any of them work. Haven't actually even made it out to Track7 yet, so whatever. :)

**Comment by dlindahl** [comment]
I'd be down for Pour House, but only if we can be certain that there is no live music. Great place, but it'd be a terrible location for chit chat if a band is around.

Bier Garden would be a great venue, but we'd have to check the weather (like you said). Wouldn't be good if its too cold.

I'd argue that Track 7 can get pretty noisy, especially if we go on a Thursday. It might be OK tho, especially if we can reserve the sectioned off tables. I mean, not sure what to expect unless we hold it in a library :D

@samt If you can check what the live band situation or table reservation policy is, we'll pick one or the other and I'll start promoting.

**Comment by a-axton** [comment]
Pour house is always good! +1

**Comment by samt** [comment]
Pour House has a music event every Thursday, but it never starts until 10pm, so we're in the clear!

Lets give this place a shot.

**Comment by dlindahl** [comment]
@samt FYI, 18 people have RSVP'd for tomorrow. Even if 50% of them show up, thats quite a few people. Keep that in mind when finding a table :smile: What time are you going to be there?

**Comment by samt** [comment]
I'll probably be there at about 5:30... maybe have to be there earlier if we're going to have people! I am surprised to see that many RSVP.

**Comment by dlindahl** [comment]
I'm pretty surprised too, but we haven't had enough events to figure out what our no show rate is at. So, take that number with a grain of salt. Plan for 18, expect less.

Not sure when I'll arrive, but it will likely be before the official kick off.

**Comment by thefatpanther** [comment]
So I _will_ be there tonight, but I will probably be late. Wife is doing field work on the bypass today & we can't leave the foster puppy alone yet so I'll have to wait till she gets home, which will probably be sometime between 5:30 & 6:30. I'll tweet you guys when I'm leaving.

**Comment by samt** [comment]
No worries, we'll see you when you get there!

**Comment by dlindahl** [comment]
Had a great turnout last night! Thanks to everyone here for their comments! :beers:
