### ISSUE TITLE
March BeerJS

### ISSUE THREAD

**Issue by dlindahl** [beerjs/sac#13]
**Date**: March 24, 2015
**Time**: 6:00pm
**Location**: [Der Biergarden](http://beergardensacramento.com/) ([Map](https://www.google.com/maps/place/Der+Biergarten/@38.574006,-121.475368,17z/data=!3m1!4b1!4m2!3m1!1s0x809ad0c3c96c80b9:0x1e22ff2da4d584a2))
**Meetup**: [RSVP](http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/221251253/)

---

Might as well start planning! :tada: :beers: 

Let's pick a date first. Thursdays are generally out for me due to The Sloppy Moose Running Club. Though... it would be interesting to see a crossover event if people are interested. But I digress.

**Comment by samt** [comment]
Wednesdays don't typically work for me (at least until mid-may). Tuesdays are generally good for quiet evenings. This week, as it so happens, is beer week, so most places will be packed every evening.

**Comment by samt** [comment]
How about Tuesday, March 24th at Biergarden?

**Comment by dlindahl** [comment]
:+1:

**Comment by machadolab** [comment]
BeerJS tonight or Saturday? Website says Saturday. This thread says today.

**Comment by samt** [comment]
@machadolab  Website lies, it's today :beer:

**Comment by dlindahl** [comment]
Oops. Good catch! Fixed the typo. :beers: See you tonight!

**Comment by samt** [comment]
Another successful beerjs! :+1:
