### ISSUE TITLE
September 2015 CoffeeJS

### ISSUE THREAD

**Issue by dlindahl** [beerjs/sac#16]
**Date**: Saturday, September 26, 2015
**Time**: 9:00am
**Location**: [Temple Coffee Roasters](http://templecoffee.com/about/locations/) on S St. ([Map](https://www.google.com/maps/place/Temple+Coffee+Roasters/@38.5639525,-121.4723742,19.96z/data=!4m7!1m4!3m3!1s0x809ad0ed95d89669:0x7cc9a801f0bb8d33!2s2829+S+St,+Sacramento,+CA+95816!3b1!3m1!1s0x0000000000000000:0x2499d36f3fbd42ab))
**Meetup**: [RSVP](http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/225562244//)

---

**Comment by a-axton** [comment]
sweet, I'm in
